- name: Copy dump_snapshot.sh/restore_snapshot.sh
  copy:
    src: "blockchain/{{item}}"
    dest: /workspace
    mode: 0700
  with_items:
  - dump_snapshot.sh
  - restore_snapshot.sh

- name: Directory 'snapshots' created
  file:
    path=/workspace/snapshots
    state=directory

- name: Blockchain snapshot downloaded
  get_url:
    url: http://lisk.prolina.org/snapshots/lisk_test_h4928450_2018-04-11T21:50:33Z.pg_dump_dump
    checksum: "sha256:9310328318ca0a34f881c6a9394d8ee363ecaa675250b9e8b001a282983a34f3"
    dest: /workspace/snapshots/lisk_test_snapshot.pg_dump_dump
    # use tmp_dest to work around https://github.com/ansible/ansible/issues/18894
    tmp_dest: /tmp

- name: Restore from snapshot
  shell: ./restore_snapshot.sh /workspace/snapshots/lisk_test_snapshot.pg_dump_dump && touch /workspace/snapshots/restored.yes
  args:
    chdir: /workspace
    creates: /workspace/snapshots/restored.yes
