- name: Blockchain snapshot downloaded
  get_url:
    url: https://testnet-snapshot.mylisk.com/blockchain.db.gz
    dest: /workspace/lisk/blockchain.db.gz

- name: Restore from snapshot
  shell: ./lisk.sh rebuild -f blockchain.db.gz && ./lisk.sh stop_node
  args:
    chdir: /workspace/lisk
    creates: /workspace/lisk/logs/lisk.log
