- name: Copy dump_snapshot.sh/restore_snapshot.sh
  copy:
    src: "blockchain/{{item}}"
    dest: /workspace
    mode: 0700
  with_items:
  - dump_snapshot.sh
  - restore_snapshot.sh

- name: Directory 'snapshots' created
  file:
    path=/workspace/snapshots
    state=directory

- name: Blockchain snapshot downloaded
  get_url:
    url: "{{ snapshot_url }}"
    checksum: "sha256:{{ snapshot_sha256 }}"
    dest: /workspace/snapshots/lisk_test_snapshot.pg_dump_dump
    # use tmp_dest to work around https://github.com/ansible/ansible/issues/18894
    tmp_dest: /tmp

- name: Restore from snapshot
  shell: ./restore_snapshot.sh /workspace/snapshots/lisk_test_snapshot.pg_dump_dump && touch /workspace/snapshots/restored.yes
  args:
    chdir: /workspace
    creates: /workspace/snapshots/restored.yes
